package com.rushro2m.greendao_master.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rushro2m.greendao_master.bean.MovieBean;

import com.rushro2m.greendao_master.bean.MovieBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieBeanDaoConfig;

    private final MovieBeanDao movieBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieBeanDaoConfig = daoConfigMap.get(MovieBeanDao.class).clone();
        movieBeanDaoConfig.initIdentityScope(type);

        movieBeanDao = new MovieBeanDao(movieBeanDaoConfig, this);

        registerDao(MovieBean.class, movieBeanDao);
    }
    
    public void clear() {
        movieBeanDaoConfig.clearIdentityScope();
    }

    public MovieBeanDao getMovieBeanDao() {
        return movieBeanDao;
    }

}
